@baseUrl = http://localhost:8000
@contentType = Content-Type: application/json
@adminToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIzLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc2NDkzMjEzOCwiZXhwIjoxNzY0OTM5MzM4fQ.ZuAGOqJJHa9wCTWnsTzHj-TGBw02AwcmPQhL20bPaOc
@userToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI4LCJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzYxNzI3MDk1LCJleHAiOjE3NjE3MzQyOTV9.EhHX_3DQ4_L9e-gCX3DzVrSK2ytmbc8bXEXPO2D5mAc

### Create User 
POST {{baseUrl}}/auth/signup
{{contentType}}

{
  "name": "JJ Jakes",
  "email": "admin@gmail.com",
  "password": "password123",
  "phone": "+1234567890",
  "role": "Admin"
}

###
POST {{baseUrl}}/auth/signin
{{contentType}}

{
  "email": "admin@gmail.com",
  "password": "password123"
}

###
GET {{baseUrl}}/users/get-all
Authorization: Bearer {{adminToken}}

###
POST {{baseUrl}}/auth/signup
{{contentType}}

{
  "name": "Admin test",
  "email": "testadmin@gmail.com",
  "password": "password123",
  "phone": "+1234567890",
  "role": "Admin"
}

###
GET {{baseUrl}}/users/get-all
Authorization: Bearer {{adminToken}}

###
GET {{baseUrl}}/users/get-user/3
Authorization: Bearer {{adminToken}}


###
GET {{baseUrl}}/seed/all

### Run Migrations
POST {{baseUrl}}/migrate

### Check Migration Status
GET {{baseUrl}}/migration-status

### Run Database Seed (after migrations)
GET {{baseUrl}}/seed/all
